
title: CV Teodor Carlsson
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Teodor Carlsson
tagline: Studying the Master Programme in Computer and Information Engineering at Uppsala University
pic: me100px2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: teodor.carlsson@hotmail.com
phone: 07-621 313 12
website: blog.webjeda.com #do not add http://
linkedin: teodor-carlsson
github: {TeodorCarlsson,Tejjsho}
twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
